# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\KTLT\Mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 410, 151, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_n = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_n.setGeometry(QtCore.QRect(340, 140, 181, 20))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.label_n = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_n.setGeometry(QtCore.QRect(280, 140, 47, 13))
        self.label_n.setObjectName("label_n")
        self.label_m = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_m.setGeometry(QtCore.QRect(280, 180, 47, 13))
        self.label_m.setObjectName("label_m")
        self.label_d = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_d.setGeometry(QtCore.QRect(280, 220, 47, 13))
        self.label_d.setObjectName("label_d")
        self.label_p = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_p.setGeometry(QtCore.QRect(270, 300, 47, 13))
        self.label_p.setObjectName("label_p")
        self.lineEdit_m = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_m.setGeometry(QtCore.QRect(340, 180, 181, 20))
        self.lineEdit_m.setObjectName("lineEdit_m")
        self.lineEdit_d = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_d.setGeometry(QtCore.QRect(340, 220, 181, 20))
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.lineEdit_p = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_p.setGeometry(QtCore.QRect(340, 300, 181, 20))
        self.lineEdit_p.setObjectName("lineEdit_p")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.label_n.setText(_translate("MainWindow", "N:"))
        self.label_m.setText(_translate("MainWindow", "M:"))
        self.label_d.setText(_translate("MainWindow", "D:"))
        self.label_p.setText(_translate("MainWindow", "P(X=1):"))
