# Form implementation generated from reading ui file 'D:\ToiDiDaoCode\24\lucky_game.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 383)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(90, 70, 61, 81))
        self.label_1.setAutoFillBackground(False)
        self.label_1.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: red;\n"
"font-weight: bold;\n"
"font-size: 48px;\n"
"padding: 5px;")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 70, 61, 81))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: red;\n"
"font-weight: bold;\n"
"font-size: 48px;\n"
"padding: 5px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 70, 61, 81))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: red;\n"
"font-weight: bold;\n"
"font-size: 48px;\n"
"padding: 5px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 190, 141, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 240, 141, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 200, 61, 21))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 250, 61, 21))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_8.setObjectName("label_8")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 300, 431, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.random = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.random.setObjectName("random")
        self.horizontalLayout.addWidget(self.random)
        self.newgame = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.newgame.setObjectName("newgame")
        self.horizontalLayout.addWidget(self.newgame)
        self.exit = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lucky game"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Lucky Game:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Player money:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Machine money:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "100"))
        self.label_8.setText(_translate("MainWindow", "100"))
        self.random.setText(_translate("MainWindow", "Random"))
        self.newgame.setText(_translate("MainWindow", "New game"))
        self.exit.setText(_translate("MainWindow", "Exit"))
