# Form implementation generated from reading ui file 'D:\ToiDiDaoCode\33\Array.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 518)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.label.setObjectName("label")
        self.label_o = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_o.setGeometry(QtCore.QRect(20, 50, 501, 31))
        self.label_o.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_o.setText("")
        self.label_o.setObjectName("label_o")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 161, 31))
        self.label_3.setObjectName("label_3")
        self.label_r = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_r.setGeometry(QtCore.QRect(20, 150, 501, 31))
        self.label_r.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_r.setText("")
        self.label_r.setObjectName("label_r")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(39, 219, 481, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_ra = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_ra.setObjectName("pushButton_ra")
        self.gridLayout.addWidget(self.pushButton_ra, 0, 0, 1, 1)
        self.pushButton_coe = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_coe.setObjectName("pushButton_coe")
        self.gridLayout.addWidget(self.pushButton_coe, 2, 0, 1, 1)
        self.pushButton_se = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_se.setObjectName("pushButton_se")
        self.gridLayout.addWidget(self.pushButton_se, 0, 1, 1, 1)
        self.pushButton_sooe = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_sooe.setObjectName("pushButton_sooe")
        self.gridLayout.addWidget(self.pushButton_sooe, 3, 0, 1, 1)
        self.pushButton_soa = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_soa.setObjectName("pushButton_soa")
        self.gridLayout.addWidget(self.pushButton_soa, 1, 0, 1, 1)
        self.pushButton_idv = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_idv.setObjectName("pushButton_idv")
        self.gridLayout.addWidget(self.pushButton_idv, 1, 1, 1, 1)
        self.pushButton_sascending = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_sascending.setObjectName("pushButton_sascending")
        self.gridLayout.addWidget(self.pushButton_sascending, 2, 1, 1, 1)
        self.pushButton_sdescending = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_sdescending.setObjectName("pushButton_sdescending")
        self.gridLayout.addWidget(self.pushButton_sdescending, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Â rây"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Original Array: </span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Result:</span></p></body></html>"))
        self.pushButton_ra.setText(_translate("MainWindow", "Random Array"))
        self.pushButton_coe.setText(_translate("MainWindow", "Count Odd Element"))
        self.pushButton_se.setText(_translate("MainWindow", "Smallest Element"))
        self.pushButton_sooe.setText(_translate("MainWindow", "Sum of Odd Element"))
        self.pushButton_soa.setText(_translate("MainWindow", "Sum of Array"))
        self.pushButton_idv.setText(_translate("MainWindow", "Increment double Value"))
        self.pushButton_sascending.setText(_translate("MainWindow", "Sort - Ascending"))
        self.pushButton_sdescending.setText(_translate("MainWindow", "Sort - Descending"))
